# Generated by Django 5.2 on 2025-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_candidate_max_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='jobdescription',
            new_name='job_description',
        ),
    ]
